[project]
name = "FreeP2W"
version = "0.1.0"
description = "The best method for PDF to Word"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fire==0.7.1",
    "fonttools==4.60.1",
    "lxml==6.0.2",
    "numpy==2.2.6",
    "opencv-python-headless==4.11.0.86",
    "python-docx==1.2.0",
    "termcolor==3.1.0",
    "typing-extensions==4.15.0",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "surya-ocr>=0.17.0",
    "psutil>=7.1.1",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
